// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Whas.Server.Data;

#nullable disable

namespace Whas.Server.Data.Migrations
{
    [DbContext(typeof(WhasDb))]
    [Migration("20261001182425_AddMatchOptions")]
    partial class AddMatchOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Whas.Server.Data.Deck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<long[]>("SpellIds")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Whas.Server.Data.DesyncReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BuildIdA")
                        .HasColumnType("text");

                    b.Property<string>("BuildIdB")
                        .HasColumnType("text");

                    b.Property<string>("HashA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReferenceSlot")
                        .HasColumnType("integer");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<long>("SuspectPlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Turn")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SuspectPlayerId");

                    b.ToTable("DesyncReports");
                });

            modelBuilder.Entity("Whas.Server.Data.Match", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BuildId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("RulesetVersion")
                        .HasColumnType("integer");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("WinnerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Whas.Server.Data.MatchPlayer", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoundDecksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RoundsWon")
                        .HasColumnType("integer");

                    b.HasKey("MatchId", "Slot");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Whas.Server.Data.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Whas.Server.Data.SpellDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ComponentsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvaluatorVersion")
                        .HasColumnType("integer");

                    b.Property<string>("GlyphsHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GlyphsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<string>("StatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "GlyphsHash", "EvaluatorVersion");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Whas.Server.Data.SpellUsage", b =>
                {
                    b.Property<long>("SpellId")
                        .HasColumnType("bigint");

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<int>("Casts")
                        .HasColumnType("integer");

                    b.HasKey("SpellId", "MatchId");

                    b.ToTable("SpellUsage");
                });

            modelBuilder.Entity("Whas.Server.Data.TurnRecord", b =>
                {
                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("Turn")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashSlot0")
                        .HasColumnType("text");

                    b.Property<string>("HashSlot1")
                        .HasColumnType("text");

                    b.Property<string>("PlanSlot0Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PlanSlot1Json")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("MatchId", "Round", "Turn");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Whas.Server.Data.Deck", b =>
                {
                    b.HasOne("Whas.Server.Data.Player", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Whas.Server.Data.MatchPlayer", b =>
                {
                    b.HasOne("Whas.Server.Data.Match", null)
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Whas.Server.Data.SpellDefinition", b =>
                {
                    b.HasOne("Whas.Server.Data.Player", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Whas.Server.Data.Match", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
